
version: '3'

services:
  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]

  hackernews:
    build: ./
    volumes:
      - ./hackerNews:/src/hackerNews
    ports:
      - "5000:5000"
    restart: always